server:
  http_listen_port: 9080  # Promtail HTTP port
  grpc_listen_port: 0  # Disable gRPC

positions:
  filename: /var/log/positions.yaml  # File to store log positions

clients:
  - url: http://loki:3100/loki/api/v1/push  # Loki push URL

scrape_configs:
  - job_name: system  # Job name
    static_configs:
      - targets:
          - localhost  # Target host
        labels:
          job: varlogs  # Job label
          __path__: /var/log/*log  # Path to log files
