# Password secret used for password hashing
password_secret = somepasswordpepper

# The SHA2 hash of the root password
root_password_sha2 = <hashed_password>

# The rest URI to access Graylog
rest_listen_uri = http://0.0.0.0:9000/api/

# The web interface URI to access Graylog
web_listen_uri = http://0.0.0.0:9000/

# Specify MongoDB server URI
mongodb_uri = mongodb://mongo:27017/graylog
